apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-coursework-deployment
  labels:
    app: devops-coursework
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: devops-coursework
  template:
    metadata:
      labels:
        app: devops-coursework
    spec:
      containers:
        - name: devops-coursework-container
          image: samy11/devops-coursework:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
