apiVersion: v1
kind: Service
metadata:
  name: devops-coursework-service
spec:
  type: NodePort
  selector:
    app: devops-coursework
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
